<?php

namespace App\Imports;

use App\Models\StockProduct;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithStartRow;

class ProductsImport implements ToModel, WithStartRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return StockProduct::updateOrCreate(
            ['ProductID' => $row[0]],
            [
                'ProductID' => $row[0],
                'ItemNum' => $row[1],
                'Name' => $row[2],
                'CatYear' => $row[3],
                'ExpirationDate' => $row[4],
                'Discontinued' => $row[5],
                'Cat1Name' => $row[6],
                'Cat2Name' => $row[7],
                'Page1' => $row[8],
                'Page2' => $row[9],
                'Description' => $row[10],
                'Keywords' => $row[11],
                'Colors' => $row[12],
                'Themes' => $row[13],
                'Dimension1' => $row[14],
                'Dimension1Units' => $row[15],
                'Dimension1Type' => $row[16],
                'Dimension2' => $row[17],
                'Dimension2Units' => $row[18],
                'Dimension2Type' => $row[19],
                'Dimension3' => $row[20],
                'Dimension3Units' => $row[21],
                'Dimension3Type' => $row[22],
                'Qty1' => $row[23],
                'Qty2' => $row[24],
                'Qty3' => $row[25],
                'Qty4' => $row[26],
                'Qty5' => $row[27],
                'Qty6' => $row[28],
                'Prc1' => $row[29],
                'Prc2' => $row[30],
                'Prc3' => $row[31],
                'Prc4' => $row[32],
                'Prc5' => $row[33],
                'Prc6' => $row[34],
                'PrCode' => $row[35],
                'PiecesPerUnit1' => $row[36],
                'PiecesPerUnit2' => $row[37],
                'PiecesPerUnit3' => $row[38],
                'PiecesPerUnit4' => $row[39],
                'PiecesPerUnit5' => $row[40],
                'PiecesPerUnit6' => $row[41],
                'QuoteUponRequest' => $row[42],
                'PriceIncludeClr' => $row[43],
                'PriceIncludeSide' => $row[44],
                'PriceIncludeLoc' => $row[45],
                'SetupChg' => $row[46],
                'SetupChgCode' => $row[47],
                'ScreenChg' => $row[48],
                'ScreenChgCode' => $row[49],
                'PlateChg' => $row[50],
                'PlateChgCode' => $row[51],
                'DieChg' => $row[52],
                'DieChgCode' => $row[53],
                'ToolingChg' => $row[54],
                'ToolingChgCode' => $row[55],
                'RepeatChg' => $row[56],
                'RepeatChgCode' => $row[57],
                'AddClrChg' => $row[58],
                'AddClrChgCode' => $row[59],
                'AddClrRunChg1' => $row[60],
                'AddClrRunChg2' => $row[61],
                'AddClrRunChg3' => $row[62],
                'AddClrRunChg4' => $row[63],
                'AddClrRunChg5' => $row[64],
                'AddClrRunChg6' => $row[65],
                'AddClrRunChgCode' => $row[66],
                'IsRecyclable' => $row[67],
                'IsEnvironmentallyFriendly' => $row[68],
                'IsNewProd' => $row[69],
                'NotSuitable' => $row[70],
                'Exclusive' => $row[71],
                'Hazardous' => $row[72],
                'OfficiallyLicensed' => $row[73],
                'IsFood' => $row[74],
                'IsClothing' => $row[75],
                'ImprintSize1' => $row[76],
                'ImprintSize1Units' => $row[77],
                'ImprintSize1Type' => $row[78],
                'ImprintSize2' => $row[79],
                'ImprintSize2Units' => $row[80],
                'ImprintSize2Type' => $row[81],
                'ImprintLoc' => $row[82],
                'SecondImprintSize1' => $row[83],
                'SecondImprintSize1Units' => $row[84],
                'SecondImprintSize1Type' => $row[85],
                'SecondImprintSize2' => $row[86],
                'SecondImprintSize2Units' => $row[87],
                'SecondImprintSize2Type' => $row[88],
                'SecondImprintLoc' => $row[89],
                'DecorationMethod' => $row[90],
                'NoDecoration' => $row[91],
                'NoDecorationOffered' => $row[92],
                'NewPictureURL' => $row[93],
                'NewPictureFile' => $row[94],
                'ErasePicture' => $row[95],
                'NewBlankPictureURL' => $row[96],
                'NewBlankPictureFile' => $row[97],
                'EraseBlankPicture' => $row[98],
                'NotPictured' => $row[99],
                'MadeInCountry' => $row[100],
                'AssembledInCountry' => $row[101],
                'DecoratedInCountry' => $row[102],
                'ComplianceList' => $row[103],
                'WarningLbl' => $row[104],
                'ComplianceMemo' => $row[105],
                'ProdTimeLo' => $row[106],
                'ProdTimeHi' => $row[107],
                'RushProdTimeLo' => $row[108],
                'RushProdTimeHi' => $row[109],
                'Packaging' => $row[110],
                'CartonL' => $row[111],
                'CartonW' => $row[112],
                'CartonH' => $row[113],
                'WeightPerCarton' => $row[114],
                'UnitsPerCarton' => $row[115],
                'ShipPointCountry' => $row[116],
                'ShipPointZip' => $row[117],
                'Comment' => $row[118],
                'Verified' => $row[119],
                'UpdateInventory' => $row[120],
                'InventoryOnHand' => $row[121],
                'InventoryOnHandAdd' => $row[122],
                'InventoryMemo' => $row[123],

                'Owner' => auth()->id()
            ]
        );
    }

    public function startRow() : int
    {
        return 8;
    }
}
